name: wardrobe
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_cropper: ^6.0.0
  path: ^1.8.0
  sqflite: ^2.0.0+3
  camera: ^0.11.0
  path_provider: ^2.0.11
  bubble_tab_indicator: ^0.1.6
  bubble_bottom_bar: ^2.0.0
  tflite: ^1.1.2
  http: ^1.2.1
  charts_flutter: ^0.12.0
  characters: ^1.2.0
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/model/labels.txt
    - assets/model/model.tflite
    - assets/model/model2.tflite
    - assets/model/colorLabels.txt
    - assets/model/colorModel.tflite
